# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifeq ($(config),debug)
  OBJDIR     = build/debug
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/transm
  DEFINES   += 
  INCLUDES  += 
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -g 
  CXXFLAGS  += $(CFLAGS) -std=c++11
  LDFLAGS   += 
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) $(OBJECTS) -o $(TARGET)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/release
  TARGETDIR  = bin
  TARGET     = $(TARGETDIR)/transm
  DEFINES   += 
  INCLUDES  += 
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -Wall -O3
  CXXFLAGS  += $(CFLAGS) -std=c++11
  LDFLAGS   += -Wl,-x
  LIBS      += 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) $(OBJECTS) -o $(TARGET)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	source/util/rand/RandomNums.o \
	source/util/Util.o	\
	source/util/HighResolutionTimerPosix.o \
	source/statistics/InfectionsTracker.o \
	source/statistics/PopStats.o \
	source/statistics/CostsTracker.o	\
	source/statistics/TransmissionSummaryStats.o	\
	source/graphviz/graphVizParse.o \
	source/entities/entitypool/bucket/BucketAge.o \
	source/entities/entitypool/bucket/BucketSexualMixing.o \
	source/entities/entitypool/bucket/DmgProfileBucket.o \
	source/entities/entitypool/bucket/FullVector.o \
	source/entities/entitypool/EntityPool.o \
	source/entities/classifiers/DmgProfile.o \
	source/entities/classifiers/SexualPartnership.o \
	source/entities/behaviors/SexualBehaviorParams.o \
	source/entities/Female.o \
	source/entities/Male.o \
	source/entities/Person.o \
	source/data/Enum.o \
	source/cepacbridge/CepacInputParser.o \
	source/Constants.o \
	source/Population.o \
	source/PopulationParams.o \
	source/Simulation.o \
	source/cepac/AcuteOIUpdater.o	\
	source/cepac/BeginMonthUpdater.o	\
	source/cepac/BehaviorUpdater.o	\
	source/cepac/CD4HVLUpdater.o	\
	source/cepac/CD4TestUpdater.o	\
	source/cepac/CepacUtil.o	\
	source/cepac/CHRMsUpdater.o	\
	source/cepac/ClinicVisitUpdater.o	\
	source/cepac/DrugEfficacyUpdater.o	\
	source/cepac/DrugToxicityUpdater.o	\
	source/cepac/EndMonthUpdater.o	\
	source/cepac/HIVInfectionUpdater.o	\
	source/cepac/HIVTestingUpdater.o	\
	source/cepac/HVLTestUpdater.o	\
	source/cepac/MortalityUpdater.o	\
	source/cepac/mtrand.o	\
	source/cepac/Patient.o	\
	source/cepac/RunStats.o	\
	source/cepac/SimContext.o	\
	source/cepac/StateUpdater.o	\
	source/cepac/SummaryStats.o	\
	source/cepac/TBDiseaseUpdater.o	\
	source/cepac/Tracer.o \
	source/statistics/ArtRolloutTracker.o \
	source/statistics/TabularOutput.o \
	source/statistics/BucketCounter.o

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking transm
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning transm
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

%.o: %.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
